#pragma once
#include <string>
#include "../Apo/endpoint.h"
namespace dm::apo {
inline std::wstring communityConfig(const wchar_t* name){HKEY key=nullptr;if(RegOpenKeyExW(HKEY_LOCAL_MACHINE,L"SOFTWARE\\DOT MIC\\Community",0,KEY_QUERY_VALUE|KEY_WOW64_64KEY,&key)!=ERROR_SUCCESS)return L"";wchar_t text[4096]{};DWORD bytes=sizeof(text),type=0;auto error=RegQueryValueExW(key,name,nullptr,&type,reinterpret_cast<BYTE*>(text),&bytes);RegCloseKey(key);if(error!=ERROR_SUCCESS||type!=REG_SZ||bytes<2||bytes>sizeof(text)||(bytes%2)||text[bytes/2-1]!=L'\0')return L"";return text;}
inline std::wstring communityProperty(IMMDevice* endpoint,const PROPERTYKEY& key){ComPtr<IPropertyStore> store;PROPVARIANT value{};std::wstring text;if(SUCCEEDED(endpoint->OpenPropertyStore(STGM_READ,&store))&&SUCCEEDED(store->GetValue(key,&value))){if(value.vt==VT_LPWSTR&&value.pwszVal)text=value.pwszVal;else if(value.vt==VT_CLSID&&value.puuid){wchar_t guid[40]{};StringFromGUID2(*value.puuid,guid,40);text=guid;}}PropVariantClear(&value);return text;}
inline HRESULT communityEndpoint(IMMDevice** result){*result=nullptr;auto stable=communityConfig(L"StableId"),container=communityConfig(L"ContainerId"),physical=communityConfig(L"PhysicalInterface"),cached=communityConfig(L"CachedEndpointId");if(stable.empty()&&(container.empty()||physical.empty()))return HRESULT_FROM_WIN32(ERROR_NOT_FOUND);ComPtr<IMMDeviceEnumerator> enumerator;auto hr=CoCreateInstance(__uuidof(MMDeviceEnumerator),nullptr,CLSCTX_ALL,IID_PPV_ARGS(&enumerator));if(FAILED(hr))return hr;
 auto match=[&](IMMDevice* device,bool fallback){ComPtr<IMMEndpoint> flow;EDataFlow direction=eAll;DWORD state=0;if(FAILED(device->QueryInterface(IID_PPV_ARGS(&flow)))||FAILED(flow->GetDataFlow(&direction))||direction!=eCapture||FAILED(device->GetState(&state))||state!=DEVICE_STATE_ACTIVE)return false;if(!container.empty()&&_wcsicmp(container.c_str(),communityProperty(device,PKEY_Device_ContainerId).c_str())!=0)return false;if(!fallback)return !stable.empty()&&stable==communityProperty(device,GateStableIdKey);if(container.empty()||physical.empty())return false;ComPtr<IDeviceTopology> topology;ComPtr<IConnector> connector;LPWSTR id=nullptr;if(FAILED(device->Activate(__uuidof(IDeviceTopology),CLSCTX_ALL,nullptr,&topology))||FAILED(topology->GetConnector(0,&connector))||FAILED(connector->GetDeviceIdConnectedTo(&id)))return false;bool equal=id&&_wcsicmp(id,physical.c_str())==0;CoTaskMemFree(id);return equal;};
 ComPtr<IMMDeviceCollection> devices;hr=enumerator->EnumAudioEndpoints(eCapture,DEVICE_STATE_ACTIVE,&devices);if(FAILED(hr))return hr;UINT count=0;hr=devices->GetCount(&count);if(FAILED(hr))return hr;
 // Enumerate for uniqueness even if a cached runtime ID exists. Never use a name/default.
 for(bool fallback:{false,true}){ComPtr<IMMDevice> chosen;for(UINT i=0;i<count;++i){ComPtr<IMMDevice> device;hr=devices->Item(i,&device);if(FAILED(hr))return hr;if(match(device.Get(),fallback)){if(chosen)return HRESULT_FROM_WIN32(ERROR_DUP_NAME);chosen=device;}}if(chosen){*result=chosen.Detach();return S_OK;}}
 return HRESULT_FROM_WIN32(ERROR_NOT_FOUND);
}
}
